name: Deploy Spring Boot App to EC2

on:
  push:
    branches:
      - main  # Change this if you use a different branch
      -
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload artifact to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          chmod 400 $EC2_KEY  # Ensure key file has correct permissions
          # Install JDK 21 on the EC2 instance
          ssh -o StrictHostKeyChecking=no -i $EC2_KEY $EC2_USER@$EC2_HOST "sudo yum update -y && sudo amazon-linux-extras enable corretto8 && sudo yum install -y java-21-amazon-corretto-devel"
          
          # Upload the JAR file
          scp -o StrictHostKeyChecking=no -i $EC2_KEY target/*.jar $EC2_USER@$EC2_HOST:/home/ec2-user/app.jar
          
          # Restart the application
          ssh -o StrictHostKeyChecking=no -i $EC2_KEY $EC2_USER@$EC2_HOST "sudo systemctl restart my-spring-app.service"
