name: Deploy Spring Boot App to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          # Decode the base64-encoded SSH key and save it as a file
          echo "$PRIVATE_KEY" | base64 -d > /tmp/ec2-key.pem
          chmod 400 /tmp/ec2-key.pem  # Ensure the key file has correct permissions
          scp -i /tmp/ec2-key.pem -o StrictHostKeyChecking=no target/*.jar ${USER}@${HOST}:~/app.jar
          ssh -i /tmp/ec2-key.pem -o StrictHostKeyChecking=no ${USER}@${HOST} '
            if ! command -v java &> /dev/null || [[ $(java -version 2>&1) != *"version \"21"* ]]; then
              sudo apt-get update
              sudo apt-get install -y openjdk-21-jdk
            fi
            pkill -f app.jar || true
            nohup java -jar ~/app.jar > app.log 2>&1 &
          '